#Promise对象
Promise是异步编程的一种解决方案，ES6原生提供了`Promise`对象。

Promise，就是一个容器，保存着某个未来才会结束的事件（通常是一个异步操作）的结果。从语法上说，Promise是一个对象，从它可以获取异步操作的消息。Promise提供统一的API，各种异步操作都可以用同样的方法进行处理。

`Promise`对象有以下特点
1. 对象的状态不受外界影响。`Promise`对象代表一个异步操作，有三种状态：`Pending`（进行中）、`Resolved`（已完成，又称Fulfilled）和`Rejected`（已失败）。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。
2. 一旦状态改变，就不会再变，任何时候都可以得到这个结果。Promise对象的状态改变，只有两种可能：从`Pending`变为`Resolved`和从`Pending`变为`Rejected`。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果。就算改变已经发生了，你再对`Promise`对象添加回调函数，也会立即得到这个结果。

使用`Promise`对象，可以将异步操作以同步操作的流程表达出来，避免了层次嵌套的回调函数。而且`Promise`对象提供统一的接口，使得控制异步操作更加容易。

`Promise`也有一些缺点。首先，无法取消`Promise`，一旦新建它就会立即执行，无法中途取消。其次，如果不设置回调函数，`Promise`内部抛出的错误，不会反应到外部。第三，当处于`Pending`状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。
#基本用法
Promise对象是一个构造函数，用来生成Promise实例。
```javascript
var promise = new Promise(function(resolve, reject) {
  // ... some code

  if (/* 异步操作成功 */){
    resolve(value);
  } else {
    reject(error);
  }
});
```
Promise构造函数接受一个函数作为参数，该函数的两个参数分别是`resolve`和`reject`。它们是两个函数，由JavaScript引擎提供。

`resolve`函数的作用是，将Promise对象的状态从“未完成”变为“成功”（即从`Pending`变为`Resolved`），在异步操作成功时调用，并将异步操作的结果，作为参数传递出去；`reject`函数的作用是，将Promise对象的状态从“未完成”变为“失败”（即从`Pending`变为`Rejected`），在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。

`Promise`实例生成以后，可以用`then`方法分别指定`Resolved`状态和`Reject`状态的回调函数。而`Reject`状态的回调函数是可选的。
```javascript
promise.then(function(value) {
  // success
}, function(error) {
  // failure
});
```

```
function timeout(ms) {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, ms, 'done');
  });
}

timeout(100).then((value) => {
  console.log(value);
});
```
`timeout`函数表示过一段时间后，Promise对象变成`Resloved`，然后`done`作为参数传递到`Resolved`的回调函数中。

Promise新建后就会立即执行。
```javascript
let promise = new Promise(function(resolve, reject) {
  console.log('Promise');
  resolve();
});

promise.then(function() {
  console.log('Resolved.');
});

console.log('Hi!');

// Promise
// Hi!
// Resolved
```
Promise新建后会立即执行，所以先输出`Promise`，然后promise的回调函数会等所有同步任务执行完后才执行，所以先输出`Resolved`。

resolve函数的参数除了正常的值以外，还可能是另一个Promise实例。
```javascript
var p1 = new Promise(function (resolve, reject) {
  // ...
});

var p2 = new Promise(function (resolve, reject) {
  // ...
  resolve(p1);
})
```
这时，`p2`的状态就由`p1`的状态来决定，如果`p1`的状态为`Pending`，则`p2`的回调函数会等待`p1`状态改变，如果`p1`状态改变了，则`p2`回调函数会立即执行。
#Promise.prototype.then()
`then`方法是定义在原型对象`Promise.prototype`上的。它的作用是为Promise实例添加状态改变时的回调函数。

`then`方法返回的是一个新的Promise实例，因此可以采用链式写法。
```javascript
getJSON("/posts.json").then(function(json) {
  return json.post;
}).then(function(post) {
  // ...
});
```
第一个回调函数完成以后，会将返回结果作为参数，传入第二个回调函数中。

#Promise.prototype.catch()
`Promise.prototype.catch`方法是`.then(null,rejection)`的别名，用于指定发生错误时的回调函数。
```javascript
getJSON("/posts.json").then(function(posts) {
  // ...
}).catch(function(error) {
  // 处理 getJSON 和 前一个回调函数运行时发生的错误
  console.log('发生错误！', error);
});
```
`getJSON`如果对象状态变为`Resolved`，则调用`then`函数，如果变为`Rejected`，则调用`catch`函数。如果`then`方法中抛出错误，也会被`catch`方法捕获。

如果Promise状态已经变成`Resolved`，再抛出错误是无效的。
```javascript
var promise = new Promise(function(resolve, reject) {
  resolve('ok');
  throw new Error('test');
});
promise
  .then(function(value) { console.log(value) })
  .catch(function(error) { console.log(error) });
// ok
```

一般不建议使用`then`函数中的第二个参数，应使用`catch`方法。
```javascript
// bad
promise
  .then(function(data) {
    // success
  }, function(err) {
    // error
  });

// good
promise
  .then(function(data) { //cb
    // success
  })
  .catch(function(err) {
    // error
  });
```

如果没有`catch`方法指定错误处理的回调函数，则Promise对象抛出的错误不会传递到外层代码，即不会有任何反应。
```javascript
var someAsyncThing = function() {
  return new Promise(function(resolve, reject) {
    // 下面一行会报错，因为x没有声明
    resolve(x + 2);
  });
};

someAsyncThing().then(function() {
  console.log('everything is great');
});
```

```javascript
var promise = new Promise(function(resolve, reject) {
  resolve('ok');
  setTimeout(function() { throw new Error('test') }, 0)
});
promise.then(function(value) { console.log(value) });
// ok
// Uncaught Error: test
```
上面程序能抛出异常，是因为此时Promise指定在下一轮"事件循环"再抛出错误,而此时的函数体已经运行完成，所以错误在函数体外抛出。

需要注意的是，`catch`方法返回的还是一个 Promise 对象，因此后面还可以接着调用`then`方法。

```javascript
Promise.resolve()
.catch(function(error) {
  console.log('oh no', error);
})
.then(function() {
  console.log('carry on');
});
// carry on
```
上面的代码因为没有报错，跳过了`catch`方法，直接执行后面的`then`方法。此时，要是`then`方法里面报错，就与前面的`catch`无关了。

#Promise.all()
用于将多个Promise实例，包装成一个新的Promise实例。
`var p = Promise.all([p1,p2,p3]); `
接受一个数组作为参数，也可不是数组，但需要具有Iterator接口，且返回的 每个成员都是Promise实例。如果其中有不是Promise实例，会调用`Promise.resolve`方法转换为`Promise`实例。

`p`的状态由`p1`、`p2`、`p3`决定，分成两种情况。

1. 只有`p1`、`p2`、`p3`的状态都变成`fulfilled`，`p`的状态才会变成`fulfilled`，此时`p1`、`p2`、`p3`的返回值组成一个数组，传递给`p`的回调函数。
2. 只要`p1`、`p2`、`p3`之中有一个被`rejected`，`p`的状态就变成`rejected`，此时第一个被`reject`的实例的返回值，会传递给p的回调函数。

```javascript
// 生成一个Promise对象的数组
var promises = [2, 3, 5, 7, 11, 13].map(function (id) {
  return getJSON("/post/" + id + ".json");
});

Promise.all(promises).then(function (posts) {
  // ...
}).catch(function(reason){
  // ...
});
```
#Promise.race()
`Promise.race`方法同样是将多个Promise实例，包装成一个新的Promise实例。

`var p = Promise.race([p1, p2, p3])`;
上面代码中，只要`p1`、`p2`、`p3`之中有一个实例率先改变状态，`p`的状态就跟着改变。那个率先改变的 Promise 实例的返回值，就传递给`p`的回调函数。

`Promise.race`方法的参数与`Promise.all`方法一样，如果不是 Promise 实例，就会先调用下面讲到的`Promise.resolve`方法，将参数转为 `Promise` 实例，再进一步处理。
#Promise.resolve()
将现有对象转为Promise对象。
`var jsPromise = Promise.resolve($.ajax('/whatever.json'));`
等价于
`new Promise(resolve => resolve('foo'))`

##参数是一个Promise实例
原封不动地返回这个实例。
##参数是一个thenable对象
`thenable`对象指的是具有`then`方法的对象
```javascript
let thenable = {
  then: function(resolve, reject) {
    resolve(42);
  }
};

let p1 = Promise.resolve(thenable);
p1.then(function(value) {
  console.log(value);  // 42
});
```
##参数不是具有then方法对象，或根本就不是对象
如果参数是一个原始值，或者是一个不具有then方法的对象，则`Promise.resolve`方法返回一个新的Promise对象，状态为`Resolved`。
```javascript
var p = Promise.resolve('Hello');

p.then(function (s){
  console.log(s)
});
// Hello
```
##不带任何参数
Promise.resolve方法允许调用时不带参数，直接返回一个`Resolved`状态的Promise对象。
```javascript
var p = Promise.resolve();

p.then(function () {
  // ...
});
```

`resolve`的Promise对象，是在本轮“事件循环”（event loop）的结束时，而不是在下一轮“事件循环”的开始时。
```javascript
setTimeout(function () {
  console.log('three');
}, 0);

Promise.resolve().then(function () {
  console.log('two');
});

console.log('one');

// one
// two
// three
```
上面代码中，`setTimeout(fn, 0)`在下一轮“事件循环”开始时执行，`Promise.resolve()`在本轮“事件循环”结束时执行，`console.log(’one‘)`则是立即执行，因此最先输出。

#Promise.reject()
`Promise.reject(reason)`方法也会返回一个新的 Promise 实例，该实例的状态为`rejected`。
```javascript
var p = Promise.reject('出错了');
// 等同于
var p = new Promise((resolve, reject) => reject('出错了'))

p.then(null, function (s) {
  console.log(s)
});
// 出错了
```
>`Promise.reject()`方法的参数，会原封不动地作为`reject`的理由，变成后续方法的参数。

```javascript
const thenable = {
  then(resolve, reject) {
    reject('出错了');
  }
};

Promise.reject(thenable)
.catch(e => {
  console.log(e === thenable)
})
// true
```
`Promise.reject`方法参数为`thenable`对象，执行后，`catch`方法获得参数也是`thenable`对象。

#两个有用的附加方法
ES6的Promise API提供方法不是很多，所以需要自己部署些有用的方法。
##done()
Promise对象中，要是最后一个方法抛出错误，是无法捕获到的，所以可以在最后添加done方法，将错误抛出到全局。
其实现代码：
```javascript
Promise.prototype.done = function (onFulfilled, onRejected) {
  this.then(onFulfilled, onRejected)
    .catch(function (reason) {
      // 抛出一个全局错误
      setTimeout(() => { throw reason }, 0);
    });
};
```
##finally()
`finally`方法用于指定不管Promise对象最后状态如何，都会执行的操作。它与`done`方法的最大区别，它接受一个普通的回调函数作为参数，该函数不管怎样都必须执行。
```javascript
Promise.prototype.finally = function (callback) {
  let P = this.constructor;
  return this.then(
    value  => P.resolve(callback()).then(() => value),
    reason => P.resolve(callback()).then(() => { throw reason })
  );
};
```
